---
- hosts: 127.0.0.1
  connection: local

  vars:
    user: "{{ ansible_ssh_user }}"
    ipa_ip: 10.16.19.32
    rdo_ip: 10.16.18.218
    ipa_hostname:  ipa.ayoung
    rdo_hostname:  rdo.ayoung
    password: passsword
  tasks:
    - name: create ipa host
      nova_compute:
         state: present
         login_username: "{{ ansible_ssh_user }}"
         login_password: "{{ password }}"
         login_tenant_name: IdM
         auth_url: http://10.16.17.66:5000/v2.0
         name: ipa.ayoung
         image_name: centos-7-cloud
         flavor_id: 2
         nics:
           - net-id: 8a602705-f3de-485a-b756-6044d0378c9f
         key_name: ayoung-pubkey

    - name: create rdo host
      nova_compute:
         state: present
         login_username: "{{ ansible_ssh_user }}"
         login_password: "{{ password }}"
         login_tenant_name: IdM
         auth_url: http://10.16.17.66:5000/v2.0
         name: rdo.ayoung
         image_name: centos-7-cloud
         flavor_id: 2
         nics:
           - net-id: 8a602705-f3de-485a-b756-6044d0378c9f
         key_name: ayoung-pubkey
    - name: float_ip_ipa 
      quantum_floating_ip_associate:
         login_username: "{{ ansible_ssh_user }}"
         login_password: "{{ password }}"
         login_tenant_name: IdM
         auth_url: http://10.16.17.66:5000/v2.0
         instance_name: ipa.ayoung
         ip_address: "{{ ipa_ip }}"
    - name: float_ip_rdo 
      quantum_floating_ip_associate:
         login_username: "{{ ansible_ssh_user }}"
         login_password: "{{ password }}"
         login_tenant_name: IdM
         auth_url: http://10.16.17.66:5000/v2.0
         instance_name: rdo.ayoung
         ip_address: "{{ rdo_ip }}"

    - name: install-ipa
      add_host: hostname={{ ipa_ip }} ansible_ssh_host={{ inventory_hostname }} groups=ipa
    - name: addrdo
      add_host: hostname={{ rdo_ip }} ansible_ssh_host={{ inventory_hostname }} groups=ipa

